title: K'Blog
name: "Kartik's Tech Blog"
author: Kartik Aggarwal
twitter_username: aggarwal_kartik
baseurl: "/"
description: Document my learning notes.
profile_url: "www.kartikaggarwal.me"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
